# Generated by Django 6.1 on 2026-09-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description_short", models.TextField(max_length=200)),
                ("description_long", models.TextField(max_length=500)),
                ("coordinates_x", models.FloatField()),
                ("coordinates_y", models.FloatField()),
            ],
        ),
    ]
