# Generated by Django 6.1 on 2026-09-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="description_long",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="location",
            name="description_short",
            field=models.TextField(max_length=500),
        ),
    ]
