# Generated by Django 6.1 on 2026-09-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_location_description_long_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="description_long",
            field=models.TextField(max_length=5000),
        ),
    ]
