# Generated by Django 6.1 on 2026-09-04 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_location_description_long"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("order", models.IntegerField()),
                ("alt", models.CharField(max_length=200)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.location",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="locations", to="catalog.imagefield"
            ),
        ),
    ]
