# Generated by Django 6.1 on 2026-09-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_imagefield_location_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagefield",
            name="alt",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="imagefield",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
