# Generated by Django 6.1 on 2026-09-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_imagefield_alt_alter_imagefield_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ImageField",
            new_name="Image",
        ),
    ]
