# Generated by Django 6.1 on 2026-09-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_rename_imagefield_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="file",
            field=models.ImageField(blank=True, null=True, upload_to="media/images/"),
        ),
    ]
