# Generated by Django 6.1 on 2026-09-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_image_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="url",
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(upload_to="media/images/"),
        ),
    ]
