# Generated by Django 6.1 on 2026-09-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_remove_image_url_alter_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
