# Generated by Django 6.1 on 2026-09-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_image_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="images",
        ),
    ]
