# Generated by Django 6.1 on 2026-09-08 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_remove_location_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.location",
            ),
        ),
    ]
