# Generated by Django 6.1 on 2026-09-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_image_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["order"]},
        ),
    ]
