# Generated by Django 5.2.17 on 2026-09-08 14:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_image_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="description_long",
            field=tinymce.models.HTMLField(max_length=5000),
        ),
    ]
