# Generated by Django 5.2.17 on 2026-09-12 08:43

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_alter_location_description_long"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="coordinates_x",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="coordinates_y",
            new_name="longitude",
        ),
        migrations.RemoveField(
            model_name="location",
            name="description_long",
        ),
        migrations.RemoveField(
            model_name="location",
            name="description_short",
        ),
        migrations.AddField(
            model_name="location",
            name="long_description",
            field=tinymce.models.HTMLField(
                blank=True, max_length=5000, verbose_name="Полное описание локации"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Короткое описание локации"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="alt",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Текстовое описание изображения",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                upload_to="images/", verbose_name="Путь к файлу изображения"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.location",
                verbose_name="Локация, к которой изображение привязано",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок отображения на странице локации"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Имя локации"),
        ),
        migrations.AddIndex(
            model_name="image",
            index=models.Index(fields=["order"], name="catalog_ima_order_a0cc0c_idx"),
        ),
    ]
