# Generated by Django 5.2.17 on 2026-09-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_rename_coordinates_x_location_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="alt",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Имя файла"
            ),
        ),
    ]
