# Generated by Django 5.2.17 on 2026-09-14 13:14

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_alter_image_alt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="location",
            name="long_description",
            field=tinymce.models.HTMLField(
                blank=True, verbose_name="Полное описание локации"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Долгота"),
        ),
        migrations.AlterField(
            model_name="location",
            name="short_description",
            field=models.TextField(
                blank=True, verbose_name="Короткое описание локации"
            ),
        ),
    ]
