# Generated by Django 5.2.17 on 2026-09-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_alter_location_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.FloatField(verbose_name="Долгота"),
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("title", "latitude", "longitude")},
        ),
    ]
